const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Physics,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Behaviors.Physics.Acts.CreateLimitedRevoluteJoint,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Physics.Acts.ApplyForceToward,
		C3.Behaviors.Physics.Acts.ApplyTorque,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{PlayButton: 0},
	{CrossButton: 0},
	{SoundButton: 0},
	{YesButton: 0},
	{NoButton: 0},
	{ScoreBoard: 0},
	{AboutButton: 0},
	{HomeButton: 0},
	{ReplayButton: 0},
	{Physics: 0},
	{Base: 0},
	{Circle: 0},
	{Ground: 0},
	{Ring: 0},
	{dragging: 0},
	{stik3: 0},
	{button: 0},
	{button2: 0},
	{FirstScreen: 0},
	{YourScore: 0},
	{ScoreColider: 0},
	{Text: 0},
	{Sine: 0},
	{Sprite3: 0},
	{Text3: 0},
	{overPopUp: 0},
	{Sprite: 0},
	{Text4: 0},
	{Text5: 0},
	{Mouse: 0},
	{Audio: 0},
	{Touch: 0},
	{Browser: 0},
	{LocalStorage: 0},
	{"10taptotalPlay": 0},
	{"1mtotalPlay": 0},
	{"20taptotalPlay": 0},
	{"2mtotalPlay": 0},
	{"30taptotalPlay": 0},
	{"3mtotalPlay": 0},
	{"1mHighscore": 0},
	{"2mHighscore": 0},
	{"3mHighscore": 0},
	{"10TapHighscore": 0},
	{"20TapHighscore": 0},
	{"30TapHighscore": 0},
	{exitBar: 0},
	{PlayMinutes: 0},
	{PlayTap: 0},
	{effect: 0},
	{Title: 0},
	{Rotate: 0},
	{MenuAssets: 0},
	{instruction: 0},
	{scoreBoardText: 0},
	{Text2: 0},
	{Sprite2: 0},
	{fire: 0},
	{fire2: 0},
	{ui: 0},
	{Score: 0},
	{Gamestart: 0},
	{"1mBest": 0},
	{"2mBest": 0},
	{"3mBest": 0},
	{"10TapBest": 0},
	{"20TapBest": 0},
	{"30TapBest": 0},
	{"1mTotalPlayed": 0},
	{"2mTotalPlayed": 0},
	{"3mTotalPlayed": 0},
	{"10TapTotalPlayed": 0},
	{"20TapTotalPlayed": 0},
	{"30TapTotalPlayed": 0},
	{sound: 0},
	{TapMode: 0},
	{TapModeSerial: 0},
	{MiniutesModeSerial: 0},
	{MiniutesMode: 0},
	{TImes: 0},
	{Tap: 0}
];

self.InstanceType = {
	PlayButton: class extends self.ISpriteInstance {},
	CrossButton: class extends self.ISpriteInstance {},
	SoundButton: class extends self.ISpriteInstance {},
	YesButton: class extends self.ISpriteInstance {},
	NoButton: class extends self.ISpriteInstance {},
	ScoreBoard: class extends self.ISpriteInstance {},
	AboutButton: class extends self.ISpriteInstance {},
	HomeButton: class extends self.ISpriteInstance {},
	ReplayButton: class extends self.ISpriteInstance {},
	Base: class extends self.ISpriteInstance {},
	Circle: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Ring: class extends self.ISpriteInstance {},
	stik3: class extends self.ISpriteInstance {},
	button: class extends self.ISpriteInstance {},
	button2: class extends self.ISpriteInstance {},
	FirstScreen: class extends self.ISpriteInstance {},
	YourScore: class extends self.ITextInstance {},
	ScoreColider: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	overPopUp: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	_10taptotalPlay: class extends self.ITextInstance {},
	_1mtotalPlay: class extends self.ITextInstance {},
	_20taptotalPlay: class extends self.ITextInstance {},
	_2mtotalPlay: class extends self.ITextInstance {},
	_30taptotalPlay: class extends self.ITextInstance {},
	_3mtotalPlay: class extends self.ITextInstance {},
	_1mHighscore: class extends self.ITextInstance {},
	_2mHighscore: class extends self.ITextInstance {},
	_3mHighscore: class extends self.ITextInstance {},
	_10TapHighscore: class extends self.ITextInstance {},
	_20TapHighscore: class extends self.ITextInstance {},
	_30TapHighscore: class extends self.ITextInstance {},
	exitBar: class extends self.ISpriteInstance {},
	PlayMinutes: class extends self.ISpriteInstance {},
	PlayTap: class extends self.ISpriteInstance {},
	effect: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	MenuAssets: class extends self.ISpriteInstance {},
	instruction: class extends self.ISpriteInstance {},
	scoreBoardText: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	fire: class extends self.ISpriteInstance {},
	fire2: class extends self.ISpriteInstance {},
	ui: class extends self.ISpriteInstance {}
}